version: '3.5'
services:
 zabbix-server:
  image: zabbix/zabbix-server-mysql:ubuntu-5.2-latest
  ports:
   - "10051:10051"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - ./zbx_env/var/lib/zabbix/export:/var/lib/zabbix/export:rw
   - ./zbx_env/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:rw
  links:
   - mysql-server:mysql-server
   - zabbix-java-gateway:zabbix-java-gateway
  environment:
   MYSQL_ROOT_PASSWORD: root_pwd
   MYSQL_DATABASE: zabbix
   MYSQL_USER: zabbix
   MYSQL_PASSWORD: zabbix
  depends_on:
   - mysql-server
   - zabbix-java-gateway
  networks:
   zbx_net_backend:
   zbx_net_frontend:
  restart: unless-stopped

 zabbix-web-apache-mysql:
  image: zabbix/zabbix-web-apache-mysql:ubuntu-5.2-latest
  ports:
   - "80:8080"
   - "443:8443"
  links:
   - mysql-server:mysql-server
   - zabbix-server:zabbix-server
  volumes:
   - /etc/localtime:/etc/localtime:ro
  environment:
   MYSQL_ROOT_PASSWORD: root_pwd
   MYSQL_DATABASE: zabbix
   MYSQL_USER: zabbix
   MYSQL_PASSWORD: zabbix
  depends_on:
   - mysql-server
   - zabbix-server
  healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost:8080/"]
   interval: 10s
   timeout: 5s
   retries: 3
   start_period: 30s
  networks:
   zbx_net_backend:
   zbx_net_frontend:
  restart: unless-stopped

 zabbix-java-gateway:
  image: zabbix/zabbix-java-gateway:ubuntu-5.2-latest
  ports:
   - "10052:10052"
  volumes:
   - ./zbx_env/usr/sbin/zabbix_java/ext_lib:/usr/sbin/zabbix_java/ext_lib:rw
  networks:
   zbx_net_backend:
  restart: unless-stopped
    
 mysql-server:
  image: mysql:8.0
  command:
   - mysqld
   - --character-set-server=utf8
   - --collation-server=utf8_bin
   - --default-authentication-plugin=mysql_native_password
  volumes:
   - ./zbx_env/var/lib/mysql:/var/lib/mysql:rw
  environment:
   MYSQL_ROOT_PASSWORD: root_pwd
   MYSQL_DATABASE: zabbix
   MYSQL_USER: zabbix
   MYSQL_PASSWORD: zabbix
  networks:
   zbx_net_backend:
  restart: unless-stopped
    
networks:
  zbx_net_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.236.0/24
  zbx_net_backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.237.0/24
